apiVersion: v1
kind: PersistentVolume
metadata:
  name: travel-platform-mysql-pv
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: travel-platform
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/local/travel-platform/mysql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: travel-platform
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: travel-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: travel-platform-mysql-pv

